feat_csv: '/tmp/LXKDATA/result_intermediate/acoustic_loop_feats_0922.csv'
nodemode: 'vowel'
dataloader: 'IterDataset'
feat_type: 'articulation'
model: 'GAT1NN2ARTICU'
checkpoint: False
migration: False
model_dir: 'models/nn_model/GAT1NN2ARTICU/'
earlystop: 10
input_dim: 30
nfeat: 10
n_hidden: 32
n_heads: 3
dropout: 0.2
out_channel: 8
include_edges: True
sample_rate: 0.5
EPOCHS: 200
BATCH_SIZE: 128
LEARNING_RATE: 0.008
NUM_FEATURES: 20
# gnncustom基础上进行试验，对标签进行标准化