feat_csv: '/tmp/LXKDATA/result_intermediate/acoustic_loop_feats_0922.csv'
nodemode: 'vowel'
dataloader: 'IterDataset'
feat_type: 'mfcc'
model: 'GAT1NN2MFCC'
checkpoint: False
migration: False
model_dir: 'models/nn_model/GAT1NN2MFCC_1/'
earlystop: 10
nfeat: 64
n_hidden: 128
n_heads: 3
dropout: 0.2
out_channel: 32
include_edges: True
sample_rate: 1
EPOCHS: 100
BATCH_SIZE: 512
LEARNING_RATE: 0.01
NUM_FEATURES: 20
# gnncustom基础上进行试验，对标签进行标准化