feat_csv: '/tmp/LXKDATA/result_intermediate/acoustic_loop_feats_sel_1w.csv'
feat_type: 'gop_loop_featnorm'
nodemode: 'vowel'
dataloader: 'gnn_dataloader'
model: 'GAT1'
checkpoint: False
migration: False
model_dir: 'models/nn_model/GAT1_4/'
modality: 'video'
earlystop: 20
nfeat: 30
n_hidden: 32
n_heads: 4
dropout: 0.25
out_channel: 16
include_edges: True
sample_rate: 1
EPOCHS: 200
BATCH_SIZE: 512
LEARNING_RATE: 0.01
NUM_FEATURES: 84