feat_csv: '/tmp/LXKDATA/result_intermediate/acoustic_visual_loop_feats_sel_3w.csv'
feat_type: 'loop_v_featnorm'
nodemode: 'vowel'
dataloader: 'gnn_dataloader'
model: 'GAT1AV'
checkpoint: False
migration: False
model_dir: 'models/nn_model/GAT1AV_2/'
modality: 'video'
earlystop: 10
nfeat: 10
n_hidden: 16
n_heads: 3
dropout: 0.25
out_channel: 16
include_edges: True
sample_rate: 1
EPOCHS: 200
BATCH_SIZE: 512
LEARNING_RATE: 0.01
NUM_FEATURES: 84