feat_csv: '/tmp/LXKDATA/result_intermediate/acoustic_loop_feats_0705.csv'
feat_type: 'loop_featnorm'
nodemode: 'vowel'
dataloader: 'gnn_dataloader'
model: 'GAT1NN7'
checkpoint: False
migration: False
model_dir: 'models/nn_model/GAT1NN7_1/'
earlystop: 20
n_hidden: 64
n_heads: 3
dropout: 0.6
out_channel: 8
include_edges: True
sample_rate: 0.2
EPOCHS: 300
BATCH_SIZE: 512
LEARNING_RATE: 0.005
NUM_FEATURES: 84
