feat_csv: '/tmp/LXKDATA/result_intermediate/acoustic_loop_feats_sel_3w.csv'
feat_type: 'loop_featnorm_avi'
model_json: 'conf/lrw_resnet18_dctcn.json'
model: 'TDCNNGat1nn2'
model_dir: 'models/nn_model/TDCNNGat1nn2_v_2/'
modality: 'video'
earlystop: 20
sample_rate: 1
EPOCHS: 200
BATCH_SIZE: 32
accum_grad: 6
LEARNING_RATE: 0.005
NUM_FEATURES: 90
