feat_csv: '/tmp/LXKDATA/result_intermediate/acoustic_loop_feats_0705.csv'
feat_type: 'loop_featnorm_xy'
nodemode: 'vowel'
dataloader: 'gnn_dataloader'
model: 'GATCustom'
checkpoint: False
model_dir: 'models/nn_model/GATCustom_Y/models/'
pic_dir: 'models/nn_model/GATCustom_Y/pics/'
earlystop: 0
n_hidden: 32
n_heads: 4
dropout: 0.4
out_channel: 16
include_edges: True
sample_rate: 0.3
EPOCHS: 500
BATCH_SIZE: 1024
LEARNING_RATE: 0.0002
NUM_FEATURES: 84
# gnncustom基础上进行试验，对标签进行标准化