feat_csv: '/tmp/LXKDATA/result_intermediate/acoustic_visual_loop_feats_sel_3w.csv'
feat_path: '/tmp/LXKDATA/result_intermediate/egemaps.json'
cmvn_path: 'data/cmvn.json'
nodemode: 'vowel'
dataloader: 'gnn_dataloader'
feat_type: 'egemaps'
model: 'GAT1EG2'
checkpoint: False
migration: False
model_dir: 'models/nn_model/DNNEGE_5/'
earlystop: 20
nfeat: 20
n_hidden: 32
n_heads: 3
dropout: 0.5
out_channel: 128
include_edges: True
sample_rate: 1
EPOCHS: 200
BATCH_SIZE: 128
LEARNING_RATE: 0.05
NUM_FEATURES: 20
# gnncustom基础上进行试验，对标签进行标准化