feat_csv: 'tmp/segment.csv'
nodemode: 'vowel'
feat_dir: 'data/phasedata/crop_audio'
dataloader: 'IterDataset'
feat_type: 'melspecsegment'
model: 'ResCNN'
checkpoint: False
migration: False
model_dir: 'models/nn_model/ResCNN_melspec_1/'
accum_grad: 1
earlystop: 20
nfeat: 64
dropout: 0.2
sample_rate: 1
EPOCHS: 200
BATCH_SIZE: 64
LEARNING_RATE: 0.004
NUM_FEATURES: 256