feat_csv: 'tmp/segment.csv'
feat_dir: 'data/phasedata/ahubert'
nodemode: 'vowel'
dataloader: 'IterDataset'
feat_type: 'hubertsegment'
model: 'DNNHubert'
checkpoint: False
migration: False
model_dir: 'models/nn_model/DNNHubert/'
accum_grad: 1
earlystop: 15
nfeat: 768
n_hidden: 64
dropout: 0.2
sample_rate: 1
EPOCHS: 150
BATCH_SIZE: 128
LEARNING_RATE: 0.01
NUM_FEATURES: 768
# gnncustom基础上进行试验，对标签进行标准化