feat_csv: '/tmp/LXKDATA/result_intermediate/phase_setment_1119.csv'
# feat_path: '/tmp/LXKDATA/result_intermediate/mfcc.json'
# cmvn_path: 'data/cmvn.json'
dataloader: 'IterDataset'
checkpoint: False
migration: False
feat_type: 'wavsegment'
model: 'CNN2_MFCC'
model_dir: 'models/nn_model/CNN2_MFCC_1/models/'
pic_dir: 'models/nn_model/CNN2_MFCC_1/pics/'
earlystop: 5
sample_rate: 1
EPOCHS: 100
BATCH_SIZE: 64
LEARNING_RATE: 0.005
NUM_FEATURES: 90