feat_csv: 'tmp/segment.csv'
nodemode: 'vowel'
feat_dir: 'data/phasedata/cqcc'
dataloader: 'IterDataset'
feat_type: 'cqccsegment'
model: 'LSTM'
checkpoint: False
migration: False
model_dir: 'models/nn_model/CQCC_BLSTM_1/'
accum_grad: 1
earlystop: 20
nfeat: 13
n_layers: 2
n_hidden: 64
dropout: 0.2
bidirectional: True
sample_rate: 1
EPOCHS: 200
BATCH_SIZE: 64
LEARNING_RATE: 0.004
NUM_FEATURES: 256
# gnncustom基础上进行试验，对标签进行标准化