feat_csv: '/tmp/LXKDATA/result_intermediate/acoustic_loop_feats_0705.csv'
feat_type: 'gop_loop_featnorm'
model: 'vowelnet1'
model_dir: 'models/nn_model/vowelnet1'
earlystop: 20
sample_rate: 1
EPOCHS: 200
BATCH_SIZE: 4096
LEARNING_RATE: 0.001
NUM_FEATURES: 90