feat_csv: '/tmp/LXKDATA/result_intermediate/acoustic_loop_feats_0922.csv'
feat_path: '/tmp/LXKDATA/result_intermediate/mfcc.json'
cmvn_path: 'data/cmvn.json'
nodemode: 'vowel'
dataloader: 'gnn_dataloader'
feat_type: 'mfcc'
model: 'GAT1NN2CQCC'
checkpoint: False
migration: False
model_dir: 'models/nn_model/GAT1NN2MFCC/'
earlystop: 40
input_dim: 1040 # 13*80
nfeat: 64
n_hidden: 32
n_heads: 3
dropout: 0.4
out_channel: 32
include_edges: True
sample_rate: 1
EPOCHS: 200
BATCH_SIZE: 32
LEARNING_RATE: 0.01
NUM_FEATURES: 20
# gnncustom基础上进行试验，对标签进行标准化