feat_csv: '/tmp/LXKDATA/result_intermediate/av_loop_feats_0922.csv'
feat_type: 'loop_v_featnorm'
nodemode: 'vowel'
dataloader: 'gnn_dataloader'
model: 'GAT1NN2_AV'
checkpoint: False
migration: False
model_dir: 'models/nn_model/GAT1NN2_V_3/'
earlystop: 20
nfeat: 10
n_hidden: 8
n_heads: 3
dropout: 0.5
out_channel: 16
include_edges: True
sample_rate: 1
EPOCHS: 100
BATCH_SIZE: 1024
LEARNING_RATE: 0.01
NUM_FEATURES: 90
# gnncustom基础上进行试验，对标签进行标准化