feat_csv: 'data/result_intermediate/acoustic_loop_feats_0922.csv'
nodemode: 'vowel'
dataloader: 'IterDataset'
feat_type: 'cmlrv'
model: 'DNNCMLRV'
checkpoint: False
migration: False
model_dir: 'models/nn_model/DNNCMLRV_1/'
accum_grad: 4
earlystop: 5
nfeat: 16
n_hidden: 64
dropout: 0.2
sample_rate: 0.5
EPOCHS: 100
BATCH_SIZE: 128
LEARNING_RATE: 0.01
NUM_FEATURES: 256
# gnncustom基础上进行试验，对标签进行标准化