feat_csv: 'data/result_intermediate/phase_setment_1119_wav2vec.csv'
nodemode: 'vowel'
feat_dir: 'data/phasedata/wav2vec'
dataloader: 'IterDataset'
feat_type: 'wav2vecsegment'
model: 'DNNWAV2VEC'
checkpoint: False
migration: False
model_dir: 'models/nn_model/DNNWAV2VEC_1/'
accum_grad: 1
earlystop: 20
nfeat: 16
n_hidden: 1024
dropout: 0.2
sample_rate: 1
EPOCHS: 200
BATCH_SIZE: 128
LEARNING_RATE: 0.004
NUM_FEATURES: 256
# gnncustom基础上进行试验，对标签进行标准化