feat_csv: '/tmp/LXKDATA/result_intermediate/acoustic_loop_feats_0922.csv'
nodemode: 'vowel'
dataloader: 'IterDataset'
feat_type: 'papi_cropavi'
model: 'GAT1NN2RESNETPAPI'
checkpoint: False
migration: False
model_dir: 'models/nn_model/GAT1NN2RESNETPAPI/'
checkpoint: 'models/nn_model/GAT1NN2RESNETPAPI/models/Frenchay_fold_0_best.pt'
earlystop: 10
nfeat: 64
n_hidden: 64
n_heads: 3
dropout: 0.4
out_channel: 8
include_edges: True
sample_rate: 0.5
EPOCHS: 200
BATCH_SIZE: 128
LEARNING_RATE: 0.008
NUM_FEATURES: 20
# gnncustom基础上进行试验，对标签进行标准化

  