feat_csv: '/tmp/LXKDATA/result_intermediate/acoustic_visual_loop_feats_sel_3w.csv'
feat_type: 'loop_av_featnorm'
nodemode: 'vowel'
dataloader: 'gnn_dataloader'
model: 'GAT1NN2_AV'
checkpoint: False
migration: False
model_dir: 'models/nn_model/GAT1NN2_AV_2/'
earlystop: 20
nfeat: 30
n_hidden: 16
n_heads: 3
dropout: 0.4
out_channel: 32
include_edges: True
sample_rate: 1
EPOCHS: 200
BATCH_SIZE: 256
LEARNING_RATE: 0.01
NUM_FEATURES: 90
# gnncustom基础上进行试验，对标签进行标准化