feat_csv: '/tmp/LXKDATA/result_intermediate/acoustic_loop_feats_0922.csv'
nodemode: 'vowel'
dataloader: 'IterDataset'
feat_type: 'wav2vecloop'
model: 'LOOPDNNWAV2VEC'
checkpoint: False
migration: False
model_dir: 'models/nn_model/LOOPDNNWAV2VEC_1/'
accum_grad: 4
earlystop: 10
nfeat: 768
n_hidden: 1024
n_heads: 3
dropout: 0.3
out_channel: 128
include_edges: True
sample_rate: 0.5
EPOCHS: 200
BATCH_SIZE: 128
LEARNING_RATE: 0.008
NUM_FEATURES: 20
# gnncustom基础上进行试验，对标签进行标准化