feat_csv: '/tmp/LXKDATA/result_intermediate/av_loop_feats_0922.csv'
nodemode: 'vowel'
dataloader: 'IterDataset'
feat_type: 'lip_cmlrv'
model: 'GAT1NN2LIPCMRLV'
checkpoint: 'models/nn_model/GAT1NN2LIPCMRLV/models/Frenchay_fold_0_best.pt'
model_dir: 'models/nn_model/GAT1NN2LIPCMRLV/'
# model_dir: '/mnt/shareEEx/yangyudong/liuxiaokang/regression/models/nn_model/GAT1NN2LIPCMRLV/'
earlystop: 3
nfeat: 266 # 256 + 10
n_hidden: 64
n_heads: 3
dropout: 0.45
out_channel: 32
include_edges: True
sample_rate: 0.5
EPOCHS: 200
BATCH_SIZE: 128
LEARNING_RATE: 0.008
NUM_FEATURES: 20
# gnncustom基础上进行试验，对标签进行标准化

  