feat_csv: '/tmp/LXKDATA/result_intermediate/acoustic_loop_feats_0922.csv'
nodemode: 'vowel'
dataloader: 'IterDataset'
feat_type: 'hubert'
model: 'GAT1NN2HUBERT'
checkpoint: False
migration: False
model_dir: 'models/nn_model/GAT1NN2HUBERT/'
earlystop: 40
nfeat: 768
n_hidden: 32
n_heads: 3
dropout: 0.4
out_channel: 32
include_edges: True
sample_rate: 0.5
EPOCHS: 200
BATCH_SIZE: 32
LEARNING_RATE: 0.01
NUM_FEATURES: 20
# gnncustom基础上进行试验，对标签进行标准化