feat_csv: '/tmp/LXKDATA/result_intermediate/av_loop_feats_0922.csv'
feat_type: 'gop'
nodemode: 'vowel'
model: 'DNNDrop_2'
checkpoint: False
migration: False
model_dir: 'models/nn_model/DNN_GOP_1/'
earlystop: 20
nfeat: 2
n_hidden: 4
n_heads: 3
dropout: 0.4
out_channel: 32
include_edges: True
sample_rate: 1
EPOCHS: 200
BATCH_SIZE: 256
LEARNING_RATE: 0.01
NUM_FEATURES: 90
# gnncustom基础上进行试验，对标签进行标准化