feat_csv: '/tmp/LXKDATA/result_intermediate/acoustic_loop_feats_0705.csv'
feat_type: 'gop_loop_featnorm'
nodemode: 'vowel'
dataloader: 'geo_dataloader'
model: 'GAT'
model_dir: 'models/nn_model/GAT/models/'
pic_dir: 'models/nn_model/GAT/pics/'
n_hidden: 64
n_heads: 4
dropout: 0.6
out_channel: 14
include_edges: True
sample_rate: 0.1
EPOCHS: 150
BATCH_SIZE: 1
LEARNING_RATE: 0.0001
NUM_FEATURES: 84