feat_csv: 'tmp/segment.csv'
nodemode: 'vowel'
feat_dir: 'data/phasedata/ivector'
dataloader: 'IterDataset'
feat_type: 'ivectorsegment'
model: 'DNN'
checkpoint: False
migration: False
model_dir: 'models/nn_model/IVECTOR_DNN_1/'
accum_grad: 1
earlystop: 20
nfeat: 400
n_hidden: 64
dropout: 0.2
sample_rate: 1
EPOCHS: 200
BATCH_SIZE: 64
LEARNING_RATE: 0.004
NUM_FEATURES: 256
# gnncustom基础上进行试验，对标签进行标准化