feat_csv: '/tmp/LXKDATA/result_intermediate/acoustic_loop_feats_0705.csv'
feat_type: 'gop_loop_featnorm'
model: 'vowelnet3'
model_dir: 'models/nn_model/vowelnet3/models/'
pic_dir: 'models/nn_model/vowelnet3/pics/'
earlystop: 0
sample_rate: 1
EPOCHS: 200
BATCH_SIZE: 1024
LEARNING_RATE: 0.001
NUM_FEATURES: 90w