feat_csv: '/tmp/LXKDATA/result_intermediate/acoustic_loop_feats_0922.csv'
nodemode: 'vowel'
dataloader: 'IterDataset'
feat_type: 'vhubert'
model: 'GAT1NN2VHUBERT'
model_dir: 'models/nn_model/GAT1NN2VHUBERT/'
checkpoint: 'models/nn_model/GAT1NN2VHUBERT/models/Frenchay_fold_0_best.pt'
earlystop: 40
input_dim: 768
nfeat: 128
n_hidden: 64
n_heads: 3
dropout: 0.2
out_channel: 64
include_edges: True
sample_rate: 1
EPOCHS: 200
BATCH_SIZE: 32
LEARNING_RATE: 0.008
NUM_FEATURES: 20
# gnncustom基础上进行试验，对标签进行标准化