feat_csv: 'data/result_intermediate/acoustic_loop_feats_0922.csv'
feat_type: 'loop_featnorm'
model: 'DNNDrop_2'
model_dir: 'models/nn_model/DNNDrop_3w/'
earlystop: 20
sample_rate: 1
EPOCHS: 200
BATCH_SIZE: 128
LEARNING_RATE: 0.005
NUM_FEATURES: 90