feat_csv: '/tmp/LXKDATA/result_intermediate/acoustic_visual_loop_feats_sel_3w.csv'
feat_type: 'loop_av_featnorm'
nodemode: 'vowel'
dataloader: 'gnn_dataloader'
model: 'GAT1AV'
checkpoint: False
migration: False
model_dir: 'models/nn_model/GAT1AV_1/'
modality: 'audio-video'
earlystop: 20
nfeat: 30
n_hidden: 32
n_heads: 3
dropout: 0.2
out_channel: 32
include_edges: True
sample_rate: 1
EPOCHS: 200
BATCH_SIZE: 512
LEARNING_RATE: 0.001
NUM_FEATURES: 84