feat_csv: '/tmp/LXKDATA/result_intermediate/acoustic_loop_feats_0714.csv'
feat_type: 'gop_loop_featnorm'
nodemode: 'vowel'
dataloader: 'gnn_dataloader'
model: 'GAT3'
checkpoint: False
migration: False
model_dir: 'models/nn_model/GAT3/models/'
earlystop: 20
n_hidden: 64
n_heads: 4
dropout: 0.6
out_channel: 16
include_edges: True
sample_rate: 0.1
EPOCHS: 500
BATCH_SIZE: 512
LEARNING_RATE: 0.005
NUM_FEATURES: 84