feat_csv: '/tmp/LXKDATA/result_intermediate/acoustic_visual_loop_feats_sel_3w.csv'
feat_path: '/tmp/LXKDATA/result_intermediate/egemaps.json'
cmvn_path: 'data/cmvn.json'
dataloader: 'BaseFeatDataLoder'
checkpoint: False
migration: False
feat_type: 'egemaps'
model: 'DNNDropEge'
model_dir: 'models/nn_model/DNN_EGEMAPS_4/'
nfeat: 528
earlystop: 20
sample_rate: 1
EPOCHS: 200
BATCH_SIZE: 512
LEARNING_RATE: 0.003
NUM_FEATURES: 20
# pca