feat_csv: '/tmp/LXKDATA/result_intermediate/acoustic_loop_feats_0705.csv'
feat_type: 'loop_featnorm'
nodemode: 'vowel'
dataloader: 'gnn_dataloader'
model: 'GAT2NN3'
checkpoint: False
migration: False
model_dir: 'models/nn_model/GAT2NN3_2/'
earlystop: 20
n_hidden: 128
n_heads: 3
dropout: 0.4
out_channel: 16
include_edges: True
sample_rate: 1
EPOCHS: 500
BATCH_SIZE: 200
LEARNING_RATE: 0.0002
NUM_FEATURES: 84
# gnncustom基础上进行试验，对标签进行标准化