feat_csv: '/tmp/LXKDATA/result_intermediate/acoustic_loop_feats_sel_3w.csv'
feat_type: 'loop_featnorm'
nodemode: 'vowel'
dataloader: 'gnn_dataloader'
model: 'GAT2NN4'
checkpoint: False
migration: False
model_dir: 'models/nn_model/GAT2NN4_2/'
earlystop: 20
n_hidden: 128
n_heads: 3
dropout: 0.4
out_channel: 8
include_edges: True
sample_rate: 1
EPOCHS: 100
BATCH_SIZE: 256
LEARNING_RATE: 0.005
NUM_FEATURES: 90
# gnncustom基础上进行试验，对标签进行标准化