feat_csv: '/tmp/LXKDATA/result_intermediate/av_loop_feats_0922.csv'
feat_type: 'lip'
nodemode: 'vowel'
dataloader: 'IterDataset'
model: 'GAT1NN2LIP'
checkpoint: False
migration: False
model_dir: 'models/nn_model/GAT1NN2_LIP/'
earlystop: 20
nfeat: 10
n_hidden: 16
n_heads: 3
dropout: 0.4
out_channel: 16
include_edges: True
sample_rate: 0.7
EPOCHS: 100
BATCH_SIZE: 128
LEARNING_RATE: 0.006
NUM_FEATURES: 84
# gnncustom基础上进行试验，对标签进行标准化