feat_csv: '/tmp/LXKDATA/result_intermediate/acoustic_loop_feats_0705.csv'
feat_type: 'gop_loop_featnorm'
nodemode: 'vowel'
dataloader: 'gnn_dataloader'
model: 'GATCustom'
checkpoint: False
model_dir: 'models/nn_model/GATCustom/models/'
pic_dir: 'models/nn_model/GATCustom/pics/'
n_hidden: 128
n_heads: 4
dropout: 0.3
out_channel: 14
include_edges: True
sample_rate: 0.1
EPOCHS: 500
BATCH_SIZE: 512
LEARNING_RATE: 0.0002
NUM_FEATURES: 84